title: Hacktoberfest 2017 summit at Le Garage
description: > # this means to ignore newlines until "baseurl:"
  Le Garage will organize an Hacktoberfest summit on the 19th of October 2017
theme: jekyll-theme-cayman
