title: Hacktoberfest 2018 summit at Le Garage
description: > # this means to ignore newlines until "baseurl:"
  Le Garage will organize an Hacktoberfest summit on the 23rd of October 2018
theme: jekyll-theme-cayman
